---
- name: Install Apache
  hosts: all
  become: yes

  tasks:
    - name: Install Apapche on Ubuntu
      apt: 
        name: apache2
        state: present
      when: ansible_os_family == "Debian"
    
    - name: Install Apapche on Ubuntu
      yum: 
        name: httpd
        state: present
      when: ansible_os_family == "Redhat"
    
    - name: Start Apache
      service:
        name: "{{'apache2' if ansible_os_family == 'Debian' else 'httpd'}}"
        state: started
        enabled: yes
    