---
# tasks file for apache
- name: Install Apache
  apt:
    name: apache2
    state: present
  become: yes

- name: Start Apache
  service:
    name: apache2
    state: started
    enabled: yes
  become: yes
